/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rabotnic;

public class App {
    public static void main(String[] args) {
        WorkHuman denis = new WorkHumanHours("Denis", 18, 10, 12);
        WorkHuman dima = new WorkHumanFullTime("Dima", 23, 200);
        dima.setWorkTime(0);
        Department dep = new Department();
        dep.addWorker(denis);
        dep.addWorker(dima);
        System.out.println(dep.totalSalary());
    }
}
